### PR TITLE
#3875 Properly re-write topic references with inner topics

### LINKED ISSUE #3875: Branch filtering does not handle nested subtopics properly
## Expected Behavior
If I have nested subtopics, and the same topic is used in two different DITAVAL contexts:

```
  <topicgroup keyscope="A">
    <ditavalref href="filter_A.ditaval"/>
    <topicref href="topic.dita">  <!-- reused topic -->
      <topicref href="topic.dita#subtopic1_id"/>
      <topicref href="topic.dita#subtopic2_id"/>
      <topicref href="topic.dita#subtopic3_id"/>
    </topicref>
  </topicgroup>

  <topicgroup keyscope="B">
    <ditavalref href="filter_B.ditaval"/>
    <topicref href="topic.dita">  <!-- reused topic -->
      <topicref href="topic.dita#subtopic1_id"/>
      <topicref href="topic.dita#subtopic2_id"/>
      <topicref href="topic.dita#subtopic3_id"/>
    </topicref>
  </topicgroup>
```

then branch filtering should uniquify the topic and its nested subtopics properly.

## Actual Behavior
After the `branch-filter` preprocessing stage, the map looks like this:

```
   <topicgroup keyscope="A">
      <topicref href="topic.dita">
         <topicref href="topic.dita#subtopic1_id"/>
         <topicref href="topic.dita#subtopic2_id"/>
         <topicref href="topic.dita#subtopic3_id"/>
      </topicref>
      <ditavalref href="filter_A.ditaval"/>
   </topicgroup>

   <topicgroup keyscope="B">
      <topicref href="topic-1.dita">
         <topicref href="topic.dita#subtopic1_id" filter-copy-to="topic-1.dita#subtopic1_id"/>
         <topicref href="topic.dita#subtopic2_id" filter-copy-to="topic-1.dita#subtopic2_id"/>
         <topicref href="topic.dita#subtopic3_id" filter-copy-to="topic-1.dita#subtopic3_id"/>
      </topicref>
      <ditavalref href="filter_B.ditaval"/>
   </topicgroup>
```

(I used the `ditaot_save_preprocessing.pl` script from [here](https://github.com/chrispy-snps/DITA-ditaot-utilities) to easily obtain the preprocessing results.)

In the "B" branch, note that the top-level topic is correctly uniquified to `@href="topic-1.dita"`, but the nested subtopics are left in an unfinished state with the original `@href` and lingering `@filter-copy-to` attributes that were never used.

Because of this, the child navigation links in the final HTML output are incorrect:

* Topic in A
  * Subtopic 1 in A
  * Subtopic 2 in A
  * Subtopic 3 in A
* Topic in B         <-- correct
  * Subtopic 1 in A  <-- incorrect, should be B
  * Subtopic 2 in A  <-- incorrect, should be B
  * Subtopic 3 in A  <-- incorrect, should be B

## Possible Solution
The `@filter-copy-to` on the nested subtopics should also be applied.

I think this might be follow-up work to #3680 (Transformation fails with "URI has a fragment component" when calling a `<mapref>` with a `<ditavalref>`).

I am happy to test any patches or suggested changes.

## Steps to Reproduce
1. Download the following testcase:
   [branch_filtering_nested_subtopics.zip](https://github.com/dita-ot/dita-ot/files/8020075/branch_filtering_nested_subtopics.zip)
2. Run the following command:
   `dita -i map.ditamap -f html5 -o out`

## Environment
* DITA-OT version: 3.7
* Operating system and version:
  Linux
* How did you run DITA-OT?
  `dita` command
* Transformation type:
  HTML5

### PR DESCRIPTION
**Pull request by raducoravu**
Properly re-write topic references with ditavalrefs and inner topics

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Properly re-write topic reference hrefs with ditavalrefs and inner topic references.

## Motivation and Context
Fixes #3875

## How Has This Been Tested?
Manual using sample from #3875 and with an automated test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No docs update necessary.

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

File: src/test/java/org/dita/dost/module/BranchFilterModuleTest.java [hunk 1]
```diff
@@ -320,4 +321,63 @@ public void testDuplicateTopic() throws IOException, SAXException {
...
+                    .build());
+        }
+        job.addAll(res);
+	    m.setJob(job);
+	    final CachingLogger logger = new CachingLogger();
+	    m.setLogger(logger);
+	    m.setXmlUtils(new XMLUtils());
+	    
+	    m.processMap(URI.create("topicAnchors.ditamap")); 
+	    assertEquals("Should re-write references", "<?xml version=\"1.0\" encoding=\"UTF-8\"?><map xmlns:ditaarch=\"http://dita.oasis-open.org/architecture/2005/\" class=\"- map/map \" ditaarch:DITAArchVersion=\"1.3\" domains=\"                          (topic abbrev-d)                          (topic delay-d)                          (map ditavalref-d)                          (map glossref-d)                          (topic hazard-d)                          (topic hi-d)                          (topic indexing-d)                          (map mapgroup-d)                          (topic markup-d xml-d)                          (topic markup-d)                          (topic pr-d)                          (topic relmgmt-d)                          (topic sw-d)                          (topic ui-d)                          (topic ut-d)                          a(props deliveryTarget)\">    \n" +
```
Comment (jelovirt) [inline src/test/java/org/dita/dost/module/BranchFilterModuleTest.java:359]: `assertEquals` is not a stable solution here. This should use XML comparison assert. Also the expected XML should not be part of the Java code, it should be a file in `src/test/resources/BranchFilterModuleTest/exp/topicAnchors.ditamap`

**Review by jelovirt — CHANGES_REQUESTED** [review]

File: src/main/java/org/dita/dost/module/BranchFilterModule.java [hunk 2]
```diff
@@ -376,7 +377,7 @@ private void generateCopies(final Element topicref, final List<FilterUtils> filt
                 final List<XMLFilter> pipe = singletonList(writer);
 
                 try {
-                    job.getStore().transform(srcAbsUri, dstAbsUri, pipe);
+                	job.getStore().transform(URLUtils.removeFragment(srcAbsUri), URLUtils.removeFragment(dstAbsUri), pipe);
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/module/BranchFilterModule.java:380]: Fix indentation

**Review by jelovirt — CHANGES_REQUESTED** [review]

File: src/main/java/org/dita/dost/module/BranchFilterModule.java (hunk 2 above)
Comment (raducoravu) [reply src/main/java/org/dita/dost/module/BranchFilterModule.java]: I removed this indentation, about this particular line it's not very efficient when you have multiple topicrefs to inner topics, like for example:

            <topicref class="- map/topicref " href="topic.dita#subtopic1_id"/>
            <topicref class="- map/topicref " href="topic.dita#subtopic2_id"/>
            <topicref class="- map/topicref " href="topic.dita#subtopic3_id"/>

we end up copying the "topic.dita" over "topic-1.dita" about 3 times although only once would have been enough.
Any ideas about how we could avoid this? So somehow if "dstAbsUri" is already on disk I would probably want to avoid copying content over it.

**Review by jelovirt — APPROVED** [review]

File: src/main/java/org/dita/dost/module/BranchFilterModule.java (hunk 2 above)
Comment (chrispy-snps) [reply src/main/java/org/dita/dost/module/BranchFilterModule.java]: @jelovirt - thanks for approving this pull request!

@raducoravu mentioned above that when there are inner topics, the fix will perform redundant copies, which is not very efficient. Can you think of a way this could be improved?
