### PR TITLE
Fix for #3353, properly detect image format on keydef to image.

### LINKED ISSUE #3353: Images referenced via keyrefs have improper format value in job.xml
Let's say we have a key definition to an image:
```xml
<keydef keys="figure-key"  href="test.svg" format="svg" />
````
which is later used using the "keyref" attribute from a DITA image element.
The .job.xml will have a mapping looking like this:
```xml
<file src="file:/C://///figures/test.svg" uri="figures/test.svg"
  path="figures\test.svg" result="file:/C:/.../figures/ISO_7010_W012.svg"
  format="svg"/>
```
So the "format" attribute on the mapping is set to "svg" but the `org.dita.dost.module.ImageMetadataModule` only looks for `format="image"` and will skip over such mappings thus the width and height of the image will no longer be determined.

The problem seems to be in the method `org.dita.dost.reader.GenListModuleReader.getFormat(Attributes)` which assigns the magic `"image"` format only to image hrefs but if the have a key definition with an image reference it will leave the format as is.

### PR DESCRIPTION
**Pull request by raducoravu**
Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Properly determine that a keydef to an image has image format.

## Motivation and Context
Fixes #3353

## How Has This Been Tested?
Automatic test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No doc.

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

File: src/main/java/org/dita/dost/reader/GenListModuleReader.java [hunk 1]
```diff
@@ -644,7 +644,11 @@ private String getFormat(Attributes atts) {
             throw new IllegalArgumentException();
             //return ATTR_FORMAT_VALUE_HTML;
         } else {
-            return atts.getValue(ATTRIBUTE_NAME_FORMAT);
+            String format = atts.getValue(ATTRIBUTE_NAME_FORMAT);
+            if(format != null && org.dita.dost.util.FileUtils.isSupportedImageFile("." + format)) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/reader/GenListModuleReader.java:648]: Use static import for `isSupportedImageFile` and use space after `if`.

**Review by jelovirt — CHANGES_REQUESTED** [review]

**Comment by raducoravu** [comment]
@jelovirt I think I managed to mess this up, I did a fetch upsteam on Github and I think I broke this pull request which now has too many commits. Should I close it and open a new one? I do not think I have the knowledge to fix it in other ways.

**Comment by raducoravu** [comment]
@jelovirt I think I managed to revert the merge update I made by mistake on the branch, then performed the code review you mentioned.
