### PR TITLE
Fix for #2704 Avoid renaming non-DITA resources on branches

### LINKED ISSUE #2704: Avoid renaming non-DITA resources used in branch filtering with dvrResourceSuffix or dvrResourcePrefix specified
Let's say I have in the DITA Map a portion like this:

        <topicref href="topics/introduction.dita">
          <ditavalref href="test.ditaval">
            <ditavalmeta>
              <dvrResourceSuffix>stuff</dvrResourceSuffix>
            </ditavalmeta>      
          </ditavalref>
          <topicref href="test.pdf" format="pdf" navtitle="THIS IS MY PDF"/>
        </topicref>

Right now (even with latest DITA OT 2.x built from the develop branch) when you generate XHTML, the table of contents will have a broken reference to "teststuff.pdf".
In my opinion the dvrResourceSuffix and dvrResourcePrefix should only act upon topic references made to DITA resource, and not topic references made to non-DITA ones.

### PR DESCRIPTION
**Pull request by raducoravu**
Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Avoid renaming non-DITA resources in DITA Maps when using ditaval filters.

## Motivation and Context
Fixes #2704

## How Has This Been Tested?
Automatic test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
Avoid renaming non-DITA resources in DITA Maps when using ditaval filters.

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

File: src/main/java/org/dita/dost/module/BranchFilterModule.java [hunk 1]
```diff
@@ -596,31 +596,39 @@ private void processAttributes(final Element elem, final Branch filter) {
...
-                final FileInfo.Builder dstBuilder = new FileInfo.Builder(hrefFileInfo)
-                        .result(dstSource)
-                        .uri(dstTemp);
-                if (dstBuilder.build().format == null) {
-                    dstBuilder.format(ATTR_FORMAT_VALUE_DITA);
+                boolean isDITA = false;
+                if(hrefFileInfo != null) {
+                    isDITA = hrefFileInfo.format == null 
+                            || ATTR_FORMAT_VALUE_DITA.equals(hrefFileInfo.format) 
+                            || ATTR_FORMAT_VALUE_DITAMAP.equals(hrefFileInfo.format);
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/module/BranchFilterModule.java:603]: This should be extracted to method `isDitaFormat(String)`, like https://github.com/dita-ot/dita-ot/blob/6af23fe52d833c19c061cad9e748461cb59ca4bc/src/main/java/org/dita/dost/module/BranchFilterModule.java#L268

**Review by jelovirt — CHANGES_REQUESTED** [review]

**Review by jelovirt — APPROVED** [review]
