### PR TITLE
Properly compute topic id when using copy-to with keydefs

### LINKED ISSUE #4076: Keyrefs to content elements inside `@copy-to` topics result in bad HTML links
## Expected Behavior
Started from:
https://www.oxygenxml.com/forum/post68679.html#p68679

If I have a `@copy-to` version of a topic:

```
<topicref href="topic.dita" keys="topic1"/>
<topicref href="topic.dita" keys="topic2" copy-to="topic2.dita"/>
```

and I have keyrefs to content inside that topic:

```
<p><xref keyref="topic1/my-fig-id"/></p>
<p><xref keyref="topic2/my-fig-id"/></p>
```

then the references should resolve properly.

## Actual Behavior

References to content elements inside the `@copy-to` element have a `null` component in their anchor names, causing the link to be invalid:

```
<p class="p"><a class="xref" href="topic.html#common__my-fig-id">Figure 1</a></p>
<p class="p"><a class="xref" href="topic2.html#null__my-fig-id">topic2.html#null__my-fig-id</a></p>
```

References to the topic work correctly; only references to content inside the topic are bad.

## Possible Solution
Not sure yet.

## Steps to Reproduce
1. Download the following testcase:
   [4076.zip](https://github.com/dita-ot/dita-ot/files/10200364/4076.zip)
2. Run the following command:
   `dita --project.xml`

## Environment
* DITA-OT version: 4.0
* Operating system and version: Linux
* How did you run DITA-OT? `dita` command
* Transformation type: HTML5

### PR DESCRIPTION
**Pull request by raducoravu**
## Description
Properly compute topic id when using copy-to with keydefs

## Motivation and Context
Fixes #4076

## How Has This Been Tested?
Automatic tests

## Type of Changes

- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No doc

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

File: src/main/java/org/dita/dost/writer/KeyrefPaser.java [hunk 1]
```diff
@@ -536,6 +537,19 @@ private Attributes processElement(final Attributes atts) {
                                 String topicId = null;
                                 if (relativeTarget.getFragment() == null && !"".equals(elementId)) {
                                     topicId = getFirstTopicId(topicFile);
+                                    if(topicId == null) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/writer/KeyrefPaser.java:540]: Fix coding style, space between`if` and `(`, same for line 542.

File: src/main/java/org/dita/dost/writer/KeyrefPaser.java [hunk 2]
```diff
@@ -536,6 +537,19 @@ private Attributes processElement(final Attributes atts) {
...
+                                        String directHref = keyDef.element.attribute(ATTRIBUTE_NAME_HREF);
+                                        if(directHref != null && ! directHref.equals(href.toString())) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/writer/KeyrefPaser.java:542]: Fix coding style, don't add a space after `!`.

**Review by jelovirt — CHANGES_REQUESTED** [review]
LGTM, just fix coding style

File: src/main/java/org/dita/dost/writer/KeyrefPaser.java [hunk 3]
```diff
@@ -536,6 +537,19 @@ private Attributes processElement(final Attributes atts) {
                                 String topicId = null;
                                 if (relativeTarget.getFragment() == null && !"".equals(elementId)) {
                                     topicId = getFirstTopicId(topicFile);
+                                    if (topicId == null) {
+                                        String directHref = keyDef.element.attribute(ATTRIBUTE_NAME_HREF);
+                                        if(directHref != null && !directHref.equals(href.toString())) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/writer/KeyrefPaser.java:542]: Add space after `if`. Amend the previous style fix commit and force push instead of creating a new commit.

**Review by jelovirt — CHANGES_REQUESTED** [review]

**Review by jelovirt — APPROVED** [review]
