### PR TITLE
Fix for #3597, avoid NPE when reusing just row or cell in specialized components topic

### LINKED ISSUE #3597: NPE in NormalizeTableFilter
I'm attaching a sample DITA OT project, when published to PDF it yields this NPE:

    /Users/..dita-ot/plugins/org.dita.base/build_preprocess.xml:194: java.lang.NullPointerException
	at org.dita.dost.writer.NormalizeTableFilter.startElement(NormalizeTableFilter.java:112)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at org.dita.dost.writer.TopicFragmentFilter.startElement(TopicFragmentFilter.java:79)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.ditang.relaxng.defaults.RelaxNGDefaultsComponent.startElement(Unknown Source)

[npeinTableNormalizer.zip](https://github.com/dita-ot/dita-ot/files/5299005/npeinTableNormalizer.zip)

It is one of the automated tests which failed on our side after updating from DITA OT 3.5.1 to DITA OT 3.5.4 in the Oxygen bundled DITA OT. 
Somehow if you look in the attached project the table rows are reused by themselves in an on the fly DITA specialization which Oxygen creates when calling its "Reuse content" action. I know it's not an usual test, but in my opinion the filter should strive not to throw unhandled error and also this is a real case, the samples were provided by a client for another issue a long time ago.

### PR DESCRIPTION
**Pull request by raducoravu**
Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Avoid NullPointerException in NormalizeTableFilter when parsing specialized topics containing only rows or cells.

## Motivation and Context
Fixes #3597

## How Has This Been Tested?
Automatic test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No doc.

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

File: src/main/java/org/dita/dost/writer/NormalizeTableFilter.java [hunk 1]
```diff
@@ -108,6 +108,9 @@ public void startElement(final String uri, final String localName, final String
                 }
             }
         } else if (TOPIC_ROW.matches(cls)) {
+            if(tableState == null) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/writer/NormalizeTableFilter.java:111]: Space after `if`

File: src/main/java/org/dita/dost/writer/NormalizeTableFilter.java [hunk 2]
```diff
@@ -127,6 +130,9 @@ public void startElement(final String uri, final String localName, final String
             }
             tableState.currentColumn = 0;
         } else if (TOPIC_ENTRY.matches(cls)) {
+            if(tableState == null) {
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/writer/NormalizeTableFilter.java:133]: Space after `if`

**Review by jelovirt — CHANGES_REQUESTED** [review]

**Review by jelovirt — APPROVED** [review]
There should never be a valid DITA specialization that has a row without valid parent elements, but I suppose this is an ok addition. It's really not a bug, but an enhancement.
