### PR TITLE
Fix for #3724, properly compute absolute references to files.

### LINKED ISSUE #3724: Error in mapref stage when passing dita map as resource
I'm attaching a sample DITA project
[chemistry_crash_single_topic.zip](https://github.com/dita-ot/dita-ot/files/6242590/chemistry_crash_single_topic.zip)

on Windows I'm running this command line:
```batch
dita -i C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux\installation_preparation\overview_of_installation_process.dita ^
  --resource=C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap ^
  -f html5 ^
  --temp=tmp ^
  --clean.temp=no ^
  -v
```

then I get an error reported in the "mapref" stage:

     [mapref]   I/O error reported by XML parser processing
     [mapref]   file:/C:/Users/radu_coravu/Desktop/dita-ot-3.6/bin/tmp/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap: C:\Users\radu_coravu\Desktop\dita-ot-3.6\bin\tmp\C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap (The filename, directory name, or volume label syntax is incorrect)

As you can see the absolute path to the dita map gets concatenated to the absolute path to the temporary files folder, producing an invalid file path on Windows.
Looking in the .job.xml at the entry for the DITA Map:

```xml
        <file src="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            uri="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            path="C:\Users\radu_coravu\Downloads\chemistry_crash_single_topic\iugux.ditamap"
            result="file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap"
            format="ditamap" resource-only="true"/>
```
it is the only entry with an absolute `@path` attribute.

When the method "org.dita.dost.module.MaprefModule.processMap(FileInfo)" gets called, the input file gets computed by appending two absolute file paths one to another:

```java
    File inputFile = new File(job.tempDir, input.file.getPath());
```
which is invalid on Windows.

The same thing works on Mac because the file path does not contain a drive name and "new File(job.tempDir, input.file.getPath())" manages to produce a valid file path.

### PR DESCRIPTION
**Pull request by raducoravu**
Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

## Description
Properly compute file path from parent and child path when the child path may be absolute.

## Motivation and Context
Fixes #3724

## How Has This Been Tested?
Automatic test.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
No doc

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Review by jelovirt — COMMENTED** [review]
The new `FileUtils.getFilePath` method is basically same as `Path.resolve` or `URI.resolve`. I would prefer to change the code from

```java
File out = FileUtils.getFilePath(destDir, path);
```

to just use

```java
File out = destDir.toPath().resolve(path).toFile();
```

In the long run we should remove basically all use of `File` and replace it with `URI`, or in cases where we must use system paths, replace with `Path`.

File: src/main/java/org/dita/dost/util/FileUtils.java [hunk 1]
```diff
@@ -615,5 +615,38 @@ public static boolean directoryContains(final File directory, final File child)
...
+     * @param parent The parent file.
+     * @param path A file path which can be either absolute or relative. 
+     * @return The file path, never <code>null</code>
+     */
+    public static File getFilePath(File parent, String path) {
+        File filePath = new File(path);
+        if(!filePath.isAbsolute()) {
+            filePath = new File(parent, path);
+        }
+        return filePath;
```
Comment (jelovirt) [inline src/main/java/org/dita/dost/util/FileUtils.java:650]: If we change this to

```suggestion
        return parent.toPath().resolve(Paths.get(path)).toFile();
```

It would be an easy way to check if that tests still pass. Then the other `getFilePath` methods that call this could be inlined and made more simple. Like

```java
public static File getFilePath(File parent, File path) {
    return getFilePath(parent, path.getPath());
}
```

would be rewritten to

```java
public static File getFilePath(File parent, File path) {
    return parent.toPath().resolve(path.toPath()).toFile();
}
```

**Comment by jelovirt** [comment]
@raducoravu I pushed my suggested changes. Are you able to run the tests on Windows to see if they still work?

**Comment by raducoravu** [comment]
@jelovirt I'm confused, I do not understand where you pushed your changes.

**Comment by jelovirt** [comment]
@raducoravu I pushed my changes to your branch.

**Comment by jelovirt** [comment]
@raducoravu See https://github.com/dita-ot/dita-ot/pull/3964/commits

**Comment by jelovirt** [comment]
@raducoravu I rebased the branch on `hotfix/3.7.3` so pull with rebase when you test this on Windows.

**Comment by raducoravu** [comment]
@jelovirt I confirm that when running my original example in #3724 on Windows with your changes the mapref stage properly finds the DITA Map:

       mapref:
         [mapref] Processing file:/C:/Users/radu_coravu/Downloads/chemistry_crash_single_topic/iugux.ditamap

**Review by jelovirt — APPROVED** [review]
